name: Build Windows DLL
on: [push, workflow_dispatch]

jobs:
  build-win64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Vosk-API
        uses: actions/checkout@v4
        with:
          repository: alphacep/vosk-api
          fetch-depth: 1

      - name: Build with Docker (Dockcross)
        run: |
          cd travis
          chmod +x build-docker-win.sh
          ./build-docker-win.sh
          # После сборки проверим, где лежит файл
          echo "Поиск собранной DLL..."
          find .. -name "*.dll"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libvosk-win64
          # Используем поиск по маске, чтобы не ошибиться с папкой
          path: "**/*.dll"
          if-no-files-found: error

